---
title: "Final project Part B: Explore factors effecting income in NLSY '79 data"
output:
  html_document: default
  html_notebook: default
---

# Team members

Please list as follows the members of your team, including yourself.

Member 1:       
Member 2:     
Member 3:     
Member 4:     

# Introduction

Many factors effect a person's income over a period of years. Of course, someone's chosen profession is the principle factor. Related to this factor is level of education, since many high-paying professions require a college degree or an additional professional degree. Other factors effecting income may be due to social biases concerning gender, race or physical appearance. 

Included with this assignment are datasets containing data on income, years of education, and physical characteristics spanning 23 years for respondents to NLSY '79. 

Your assignment for Part B of the final project is

**Perform exploratory data analysis on the effects on income of combinations of other variables provided** 

Further instructions are as follows. 

1. Include in your analysis at least 3 variables besides income.

Single variant for a lot of them
Bi variant relationsips for other. Determine which two variables have the most affect.

Race, education, sex, BMI, age. 4 multivariate (Race and sex, education and race, education and sex, age and BMI, BMI and sex)

Andrew: Race, BMI, education and race, BMI and sex

Sean: education, age, education and sex

Bert: sex, Race and sex, age and BMI

2. You may restrict the data to a single year, or include multiple years to study trends. The choice is yours and depends on the features you wish to analyze.

First and last year for the sense of change over time. Comparison over time. 

3. In the first section of your report, state explicitly which variables you will analyze along with income, and the year or years of data analyzed.     

4. Survey the distribution of each individual variable included in your analysis and identify any values that may be erroneous or otherwise need special handling. State clearly how you will handle such values (remove the record from the data? replace by NA?).

5. Include in your analysis both plots and numerical summaries of key relationships, as illustrated in the included example.    
6. You should work together as a team on this project. Only one individual team member needs to submit a copy of the same solution in Canvas. The report you produce as your solution to the assignment should be given as both an RMarkdown notebook and a PDF or HTML file.

7.  You should divide the document into appropriate sections. In addition to code chunks, write textual explanations of what analyses are to be done, and any observations you have as a result of plots or numerical summaries generated.  If you create code chunks including several distinct commands, include comments in the chunk to explain your steps.

8. End the report with a separate section stating hypotheses you have about how income is effected by combinations of the variables you analyzed.    


